---
version: '2'

services:
    assets:
        image: nginx:alpine
        volumes:
            - .:/usr/share/nginx/html
            - ./nginx/nginx.assets.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/start.sh:/usr/share/nginx/start.sh
            - ./nginx/nginx.crt:/etc/nginx/ssl/server.crt
            - ./nginx/nginx.key:/etc/nginx/ssl/server.key
        ports:
            - "4400:80"
            - "4443:443"  # HTTPS port
        working_dir: /usr/share/nginx/html
        environment:
            - NODE_ENV=production
        command: ["sh", "/usr/share/nginx/start.sh"]
